{
 "title": "fastapi-app",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "logsearch" }
  ]
 },
 "panels": [
  {
   "title": "% Span <= 0.016 Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (span_name) (traces_spanmetrics_latency_bucket{le=\"0.016\",service=\"fastapi-app\"})\n/\nsum by (span_name) (traces_spanmetrics_latency_bucket{le=\"+Inf\",service=\"fastapi-app\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Requests <= 0.1 Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_request_duration_seconds_bucket{le=\"0.1\"}[1h])) \n/\nsum by (handler) (rate(http_request_duration_seconds_bucket{le=\"+Inf\"}[1h]))\n\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fastapi-logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"fastapi-app\"} |~ `(?i)$logsearch`"
    }
   ]
  }
 ]
}