global:
  scrape_interval: 10s  # Reduce this for testing

scrape_configs:
  - job_name: 'fastapi-app'
    metrics_path: /metrics  # Ensures Prometheus scrapes the correct endpoint
    static_configs:
      - targets: ['fastapi-app:8000']  # Must match the service name in docker-compose.yml
  - job_name: 'tempo'
    metrics_path: /metrics
    static_configs:
      - targets: ['tempo:3200']

