- name: Deploy Spring Boot API
  hosts: localhost
  tasks:
    - name: Create Spring Boot Deployment
      k8s:
        kubeconfig: /home/ansible/.kube/config  # Path to kubeconfig
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: springboot-api
            namespace: default  # Specify namespace
            labels:
              app: springboot-api
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: springboot-api
            template:
              metadata:
                labels:
                  app: springboot-api
                annotations:
                  prometheus.io/scrape: "true"
                  prometheus.io/port: "8881"
                  prometheus.io/path: "/actuator/prometheus"
              spec:
                containers:
                  - name: springboot-api
                    image: sumanth17121988/springbootmetric:1
                    ports:
                      - name: metrics-port
                        containerPort: 8881
                    resources:
                      limits:
                        cpu: "500m"
                        memory: "256Mi"
                      requests:
                        cpu: "250m"
                        memory: "128Mi"
                    livenessProbe:
                      httpGet:
                        path: /actuator/health/liveness
                        port: 8881
                      initialDelaySeconds: 10
                      periodSeconds: 10
                    readinessProbe:
                      httpGet:
                        path: /actuator/health/readiness
                        port: 8881
                      initialDelaySeconds: 5
                      periodSeconds: 5

    - name: Create Spring Boot Service
      k8s:
        kubeconfig: /home/ansible/.kube/config  # Path to kubeconfig
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: springboot-api-service
            namespace: default  # Specify namespace
            labels:
              prometheus: monitored
          spec:
            selector:
              app: springboot-api
            ports:
              - name: metrics-port
                protocol: TCP
                port: 8881
                targetPort: 8881
            type: LoadBalancer
